// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultServerUrl() {
  return window['go']['main']['App']['GetDefaultServerUrl']();
}

export function OpenExternalBrowser(arg1) {
  return window['go']['main']['App']['OpenExternalBrowser'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
