// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultServerUrl() {
  return window['go']['main']['App']['GetDefaultServerUrl']();
}

export function IsWindowMaximised() {
  return window['go']['main']['App']['IsWindowMaximised']();
}

export function OpenExternalBrowser(arg1) {
  return window['go']['main']['App']['OpenExternalBrowser'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
