// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultServerUrl():Promise<string>;

export function OpenExternalBrowser(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;
